[font]
size = 15

normal = {family = "LiterationMono Nerd Font Mono", style = "Regular"}
# offset = {x=1, y=10}

[env]
TERM = "xterm-256color"

# bold:
#   family: "FiraCode Nerd Font"
#   style: Bold
#
# italic:
#   family: "FiraCode Nerd Font"
#   style: Italic
#
# bold_italic:
#   family: "FiraCode Nerd Font"
#   style: Bold Italic
